version: '3'

services:
  mysql_db:
    image: mysql:latest
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 8989:3306
    env_file:
      - ./settings/dev/.env

  myadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    env_file: 
      - ./settings/dev/.env.pma
    depends_on:
      - mysql_db

  nginx:
    build: ./nginx
    ports:
      - 80:8000
    volumes:
      - build_folder:/var/www/client
    depends_on: 
      - client
      - spring-boot

  client:
    build:
      context: ./client
      args:
        API_URL: '*'
    ports:
      - 3000:3000
    volumes:
      - ./client/:/client
      - build_folder:/client/build
      - ./client/node_modules/:/client/node_modules
    environment: 
      - CI=true
    tty: true

  spring-boot:
    restart: always
    image: spring-boot
    build:
      context: ./server
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
    volumes:
      - springdata:/usr/src/mymaven:rw
      - ./server/:/server/

volumes:
  mysql_data:
  springdata:
  build_folder: