version: '3'

services:
  mysql_db:
    image: mysql:latest
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 8989:3306
    env_file:
      - ./settings/dev/.env

  myadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    env_file: 
      - ./settings/dev/.env.pma
    depends_on:
      - mysql_db

  nginx:
    build: ./nginx
    ports:
      - 80:8000
    
  # client:
  #   build:
  #     context: ./client
  #   command: ["npm", "start"]
  #   ports:
  #     - 3000:3000
  #   volumes:
  #   tty: true

  spring-boot:
    restart: always
    image: spring-boot
    build:
      context: ./server
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
    volumes:
      - springdata:/usr/src/mymaven:rw
      - ./server/:/server/

volumes:
  mysql_data:
  springdata:
